In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Defining the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9933, 7378, 812, 561],
 [9933, 7378, 812, 2225],
 [9933, 2788, 812, 6554],
 [7098, 7281, 3480, 86, 8203],
 [7098, 7281, 3480, 86, 8669],
 [4323, 9933, 6404, 812, 2095],
 [9425, 8767, 9187, 86]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9933 7378  812  561]
 [   0    0    0    0 9933 7378  812 2225]
 [   0    0    0    0 9933 2788  812 6554]
 [   0    0    0 7098 7281 3480   86 8203]
 [   0    0    0 7098 7281 3480   86 8669]
 [   0    0    0 4323 9933 6404  812 2095]
 [   0    0    0    0 9425 8767 9187   86]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 342ms/step


array([[[-0.03358247, -0.03030005, -0.04209495, -0.01954503,
         -0.01068038,  0.00464269,  0.0001376 , -0.03763753,
         -0.00334883, -0.04988752],
        [-0.03358247, -0.03030005, -0.04209495, -0.01954503,
         -0.01068038,  0.00464269,  0.0001376 , -0.03763753,
         -0.00334883, -0.04988752],
        [-0.03358247, -0.03030005, -0.04209495, -0.01954503,
         -0.01068038,  0.00464269,  0.0001376 , -0.03763753,
         -0.00334883, -0.04988752],
        [-0.03358247, -0.03030005, -0.04209495, -0.01954503,
         -0.01068038,  0.00464269,  0.0001376 , -0.03763753,
         -0.00334883, -0.04988752],
        [ 0.00633674, -0.01014053,  0.01784177,  0.00824226,
         -0.03000541, -0.03151038,  0.00963717, -0.03696429,
          0.0230686 , -0.00700342],
        [ 0.00799831,  0.01496163,  0.02066673, -0.0087529 ,
         -0.01084857, -0.02945124,  0.02899087, -0.00461872,
         -0.00452685, -0.01154447],
        [-0.03145862, -0.03219744, -0.03019038, -0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 9933, 7378,  812,  561])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 66ms/step


array([[-0.03358247, -0.03030005, -0.04209495, -0.01954503, -0.01068038,
         0.00464269,  0.0001376 , -0.03763753, -0.00334883, -0.04988752],
       [-0.03358247, -0.03030005, -0.04209495, -0.01954503, -0.01068038,
         0.00464269,  0.0001376 , -0.03763753, -0.00334883, -0.04988752],
       [-0.03358247, -0.03030005, -0.04209495, -0.01954503, -0.01068038,
         0.00464269,  0.0001376 , -0.03763753, -0.00334883, -0.04988752],
       [-0.03358247, -0.03030005, -0.04209495, -0.01954503, -0.01068038,
         0.00464269,  0.0001376 , -0.03763753, -0.00334883, -0.04988752],
       [ 0.00633674, -0.01014053,  0.01784177,  0.00824226, -0.03000541,
        -0.03151038,  0.00963717, -0.03696429,  0.0230686 , -0.00700342],
       [ 0.00799831,  0.01496163,  0.02066673, -0.0087529 , -0.01084857,
        -0.02945124,  0.02899087, -0.00461872, -0.00452685, -0.01154447],
       [-0.03145862, -0.03219744, -0.03019038, -0.02155986, -0.01857986,
        -0.00832744, -0.00501311,  0.02252699